name: Build and deploy Jekyll site to Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      # OS deps needed by Jekyll plugins (ImageMagick)
      - name: Install OS deps (ImageMagick)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      # If you convert notebooks to HTML/Markdown during build
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Jupyter
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      # If you use Mermaid diagrams during build (optional)
      # - name: Mermaid CLI
      #   run: npm install -g @mermaid-js/mermaid-cli

      - name: Build site
        run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
